apiVersion: v1
kind: Service

metadata:
  namespace: {{ .Values.namespace }}
  labels:
    service: catalogue
  name: catalogue
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: catalogue
