{{ if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRole
metadata:
  namespace: {{ .Values.namespace }}
  name: robot-shop
rules:
- apiGroups:
  - policy
  resourceNames:
  - robot-shop
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}
