# dispatch just listens to a message queue
# it does not expose any ports
apiVersion: v1

kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: dispatch
  labels:
    service: dispatch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch
