apiVersion: v1

kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    service: mongodb
  name: mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
