apiVersion: v1
kind: Service
namespace: {{ .Values.namespace }}
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
