apiVersion: v1
kind: Service
namespace: {{ .Values.namespace }}
metadata:
  labels:
    service: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    service: redis
