FROM python:3.9

# Some default values
ENV HOST="http://localhost:8080/" \
    SILENT=0 \
    NUM_CLIENTS=1 \
    ERROR=0 \
    RUN_TIME=0
    

WORKDIR /load

COPY requirements.txt /load/

RUN pip install -r requirements.txt

COPY entrypoint.sh /load/
COPY robot-shop.py /load/

# This one doesn't work when it's come to python distroless image
# Because it tries to run the bash script as the python script,
# so, we have to explicitly run the bash script

CMD ["./entrypoint.sh"]


